"""empty message

Revision ID: 42193f81f98c
Revises: 86c2fdd6aae6
Create Date: 2018-01-09 11:22:54.157749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42193f81f98c'
down_revision = '86c2fdd6aae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tx_outs_BACKUP')
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=False)
    op.drop_constraint('tx_ins_ibfk_1', 'tx_ins', type_='foreignkey')
    op.create_foreign_key(None, 'tx_ins', 'tx_outs', ['previous_id'], ['id'])
    op.create_foreign_key(None, 'tx_outs', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key(None, 'tx_outs', 'transactions', ['tx_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tx_outs', type_='foreignkey')
    op.drop_constraint(None, 'tx_outs', type_='foreignkey')
    op.drop_constraint(None, 'tx_ins', type_='foreignkey')
    op.create_foreign_key('tx_ins_ibfk_1', 'tx_ins', 'tx_outs_BACKUP', ['previous_id'], ['id'])
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.create_table('tx_outs_BACKUP',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tx_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('coin_value', mysql.DECIMAL(precision=30, scale=0), nullable=False),
    sa.Column('script', mysql.TEXT(collation='utf8_unicode_ci'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='tx_outs_BACKUP_ibfk_1'),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], name='tx_outs_BACKUP_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
