"""empty message

Revision ID: 56cc695ce09f
Revises: 
Create Date: 2018-01-09 11:33:29.492174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cc695ce09f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bitcoin_address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_bitcoin_address'), 'addresses', ['bitcoin_address'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('mercle_root', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Numeric(precision=12), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tx_count', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_block_hash'), 'blocks', ['block_hash'], unique=False)
    op.create_index(op.f('ix_blocks_height'), 'blocks', ['height'], unique=False)
    op.create_table('lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_time', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=False)
    op.create_table('block_tx',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'block_id')
    )
    op.create_table('tx_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('coin_value', sa.Numeric(precision=30), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tx_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(length=12), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_id'], ['tx_outs.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tx_ins')
    op.drop_table('tx_outs')
    op.drop_table('block_tx')
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('lock')
    op.drop_index(op.f('ix_blocks_height'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_hash'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_addresses_bitcoin_address'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
