"""empty message

Revision ID: 86c2fdd6aae6
Revises: 1b1317730c96
Create Date: 2018-01-06 01:43:01.315699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c2fdd6aae6'
down_revision = '1b1317730c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tx_outs_position'), 'tx_outs', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tx_outs_position'), table_name='tx_outs')
    # ### end Alembic commands ###
