"""empty message

Revision ID: 9f9f915a680b
Revises: 
Create Date: 2017-12-24 15:21:48.953050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9f915a680b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('mercle_root', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('previous_block_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tx_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_time', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tx_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('coin_value', sa.Numeric(precision=30), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tx_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(length=12), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['previous_id'], ['tx_outs.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tx_ins')
    op.drop_table('tx_outs')
    op.drop_table('transactions')
    op.drop_table('blocks')
    # ### end Alembic commands ###
