"""empty message

Revision ID: a7454e360da5
Revises: c722e590f73d
Create Date: 2017-12-25 15:02:12.411805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7454e360da5'
down_revision = 'c722e590f73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'height')
    # ### end Alembic commands ###
