"""empty message

Revision ID: c722e590f73d
Revises: 03ca28603cb2
Create Date: 2017-12-25 14:45:54.507743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c722e590f73d'
down_revision = '03ca28603cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocks', 'blocks', ['parent_id'], ['id'])
    op.drop_column('blocks', 'previous_block_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('previous_block_hash', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=False))
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_column('blocks', 'parent_id')
    # ### end Alembic commands ###
