"""empty message

Revision ID: e80939c65e5e
Revises: 9f9f915a680b
Create Date: 2017-12-24 15:59:40.678529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80939c65e5e'
down_revision = '9f9f915a680b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    # ### end Alembic commands ###
